/**
 * Signicat OIDC client for Norwegian BankID (NBID).
 *
 * Implements only the authorization code flow endpoints:
 *  - buildAuthorizationUrl()   — constructs the Signicat /authorize URL
 *  - exchangeCodeForClaims()   — exchanges the auth code for ID-token claims
 *
 * ID-token signature verification is intentionally omitted in this prototype;
 * in production the gateway should verify the JWT against Signicat's JWKS.
 */

import {
  SIGNICAT_CLIENT_ID,
  SIGNICAT_CLIENT_SECRET,
  SIGNICAT_ISSUER,
  GATEWAY_URL,
} from "../config";

/** The redirect URI registered with Signicat — always the gateway's callback. */
export const OIDC_REDIRECT_URI = `${GATEWAY_URL}/kyc/callback`;

/**
 * Builds the Signicat authorization URL that the mobile app opens in a
 * browser to start the BankID authentication flow.
 *
 * @param state  CSRF-protection nonce generated by the caller
 */
export function buildAuthorizationUrl(state: string): string {
  const params = new URLSearchParams({
    response_type: "code",
    client_id: SIGNICAT_CLIENT_ID,
    scope: "openid profile",
    redirect_uri: OIDC_REDIRECT_URI,
    state,
    // Request Norwegian BankID specifically
    acr_values: "urn:signicat:oidc:method:nbid",
    ui_locales: "en",
  });
  return `${SIGNICAT_ISSUER}/connect/authorize?${params}`;
}

export interface BankIdClaims {
  sub: string;
  name?: string;
  given_name?: string;
  family_name?: string;
  birthdate?: string;
  /** Norwegian national identity number (personnummer), scope-dependent. */
  nin?: string;
  [key: string]: unknown;
}

/**
 * Exchanges an authorization code for BankID identity claims.
 *
 * Calls Signicat's token endpoint, decodes the returned ID token and
 * returns the payload claims. The ID token signature is NOT verified here;
 * add JWKS-based verification before production use.
 *
 * @param code  The `code` query parameter from the OIDC callback
 */
export async function exchangeCodeForClaims(
  code: string
): Promise<BankIdClaims> {
  const body = new URLSearchParams({
    grant_type: "authorization_code",
    code,
    redirect_uri: OIDC_REDIRECT_URI,
    client_id: SIGNICAT_CLIENT_ID,
    client_secret: SIGNICAT_CLIENT_SECRET,
  });

  const tokenRes = await fetch(`${SIGNICAT_ISSUER}/connect/token`, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: body.toString(),
  });

  if (!tokenRes.ok) {
    const text = await tokenRes.text();
    throw new Error(`Signicat token exchange failed (${tokenRes.status}): ${text}`);
  }

  const tokens = await tokenRes.json() as { id_token: string };

  // Base64url-decode the JWT payload section (index 1)
  const parts = tokens.id_token.split(".");
  if (parts.length < 2 || !parts[1]) {
    throw new Error("Signicat returned a malformed ID token");
  }
  const claims = JSON.parse(
    Buffer.from(parts[1], "base64url").toString("utf8")
  ) as BankIdClaims;

  return claims;
}
